/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.13.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as actions_discord from "../actions/discord";
import type * as actions_slack from "../actions/slack";
import type * as discord from "../discord";
import type * as http from "../http";
import type * as slack from "../slack";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  "actions/discord": typeof actions_discord;
  "actions/slack": typeof actions_slack;
  discord: typeof discord;
  http: typeof http;
  slack: typeof slack;
}>;
