/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.7.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as actions_algolia from "../actions/algolia.js";
import type * as actions_discord from "../actions/discord.js";
import type * as actions_slack from "../actions/slack.js";
import type * as crons from "../crons.js";
import type * as discord from "../discord.js";
import type * as http from "../http.js";
import type * as indexing from "../indexing.js";
import type * as slack from "../slack.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "actions/algolia": typeof actions_algolia;
  "actions/discord": typeof actions_discord;
  "actions/slack": typeof actions_slack;
  crons: typeof crons;
  discord: typeof discord;
  http: typeof http;
  indexing: typeof indexing;
  slack: typeof slack;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
