# fly.toml app configuration file generated for discord-slack-bridge on 2024-10-10T19:20:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-slack-bridge'
primary_region = 'iad'

[build]

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
